#!/usr/bin/env bash
set -e
GOCACHE=off script/bootstrap
GOCACHE=off script/test

# re-run test to ensure GIT_TRACE output doesn't leak into the git package
GIT_TRACE=1 GOCACHE=off script/test git

pushd t >/dev/null
  UNAME=$(uname -s)
  X=""
  if [[ $UNAME == MINGW* || $UNAME == MSYS* || $UNAME == CYGWIN* ]]; then
    X=".exe"
  fi
  VERBOSE_LOGS=1 make X="$X" clean && make X="$X" PROVE_EXTRA_ARGS=-j9
popd >/dev/null
