#!/bin/bash

gofmt -w -l "$@" *.go

# don't run gofmt in these directories
ignored=(/bin/ /docs/ /log/ /man/ /tmp/ .vendor)
for i in */ ; do
  if [[ ! ${ignored[*]} =~ "/$i" ]]; then
    gofmt -w -l "$@" "${i%?}"
  fi
done

script/clean-git-test-fixtures > /dev/null
