#!/bin/sh

. "test/testenv.sh"

SHUTDOWN_LFS=no
SHOW_LOGS=yes

atexit() {
  if [ "$SHOW_LOGS" == "yes" ]; then
    if [ -s "$REMOTEDIR/gitserver.log" ]; then
      echo ""
      echo "gitserver.log:"
      cat "$REMOTEDIR/gitserver.log"
    fi

    echo ""
    echo "env:"
    env
  fi

  shutdown
}

trap "atexit" EXIT

if [ -s "$LFS_URL_FILE" ]; then
  SHOW_LOGS=no
  echo "$LFS_URL_FILE still exists!"
  exit 1
fi

setup

test/test-happy-path.sh

SHUTDOWN_LFS=yes
