#!/bin/sh

deps=$(go list -f '{{join .Deps "\n"}}' . | xargs go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}' | grep -v "github.com/github/git-lfs")

# exit 0 means non-vendored deps were found
if [ $? -eq 0 ];
then
  echo "Non vendored dependencies found:"
  for d in $deps; do echo "\t$d"; done
  exit 1
else
  echo "Looks good!"
fi

