#!/usr/bin/env bash
ronn=`which ronn`

if [ -x "$ronn" ]; then
  mkdir -p man
  rm -rf man/*.ronn
  rm -rf man/*.txt
  cp docs/man/*.ronn man
  cp docs/man/*.txt man
  $ronn man/*.ronn
  rm -rf man/*.ronn
  rm -rf man/*.txt
else
  echo "Install the 'ronn' ruby gem to build the man pages."
fi
