#!/usr/bin/env bash

# Compatibility with go 1.6
export GO15VENDOREXPERIMENT=0

script/fmt
commit=`git rev-parse --short HEAD`
go run -ldflags="-X github.com/github/git-lfs/lfs.GitCommit $commit" ./git-lfs.go "$@"
