#!/bin/sh
#/ Usage: script/test          # run all tests
#/        script/test <subdir> # run just a package's tests

script/fmt

export LOCALSRCDIR=`pwd`/.vendor/src/github.com/github/git-lfs
mkdir -p `dirname $LOCALSRCDIR`
rm -f $LOCALSRCDIR
ln -s `pwd` $LOCALSRCDIR

GOPATH="`pwd`/.vendor"
SUITE="./${1:-"lfs"}"
if [ $# -gt 0 ]; then
  shift
fi
PATH=$LOCALSRCDIR/bin:$PATH GOPATH=$GOPATH go test $SUITE "$@"
