= git-lfs-pointer(1)

== NAME

git-lfs-pointer - Build, compare, and check pointers

== SYNOPSIS

[source,role=synopsis,subs="verbatim,quotes"]
----
*git lfs pointer* **--file=**__path/to/file__
*git lfs pointer* **--file=**__path/to/file__ **--pointer=**__path/to/pointer__
*git lfs pointer* **--file=**__path/to/file__ *--stdin*
*git lfs pointer --check* **--file=**__path/to/file__
----

== Description

Builds and optionally compares generated pointer files to ensure
consistency between different Git LFS implementations.

== OPTIONS

`-f`::
`--file`::
  A local file to build the pointer from.
`-p`::
`--pointer`::
  A local file including the contents of a pointer generated from another
  implementation. This is compared to the pointer generated from `--file`.
`--stdin`::
  Reads the pointer from STDIN to compare with the pointer generated from
  `--file`.
`--check`::
  Reads the pointer from STDIN (if `--stdin` is given) or the filepath (if
  `--file`) is given. If neither or both of `--stdin` and `--file` are given,
  the invocation is invalid. Exits 0 if the data read is a valid Git LFS
  pointer. Exits 1 otherwise.
`--strict`::
`--no-strict`::
  In conjunction with `--check`, `--strict` verifies that the pointer is
  canonical; that is, it would be the one created by Git LFS. If it is not,
  exits 2. The default, for backwards compatibility, is `--no-strict`, but this
  may change in a future version.
`--no-extensions`::
  Don't print the extensions of the pointer.

== SEE ALSO

Part of the git-lfs(1) suite.
