package api_test

import (
	"testing"

	"github.com/github/git-lfs/api"
	"github.com/github/git-lfs/vendor/_nuts/github.com/stretchr/testify/assert"
)

// SchemaTestCase encapsulates a single assertion of equality against two
// generated RequestSchema instances.
//
// SchemaTestCases are meant only to test that the request schema generated by
// an API service matches what we expect it to be. A SchemaTestCase does not
// make use of the *api.Client, any particular lifecycle, or spin up a test
// server. All of that behavior is tested at a higher strata in the
// client/lifecycle tests.
//
// For examples, open any `*_api_test.go` file in the `api_test` package.
//
//   - Expected is the *api.RequestSchema that we expected to be generated.
//   - Got is the *api.RequestSchema that was generated by a service.
func AssertSchema(t *testing.T, expected, got *api.RequestSchema) {
	assert.Equal(t, expected, got)
}
